name: Build Exploit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc \
          libmnl-dev \
          libnftnl-dev
    
    - name: Build Exploit
      run: gcc -lmnl -lnftnl exploit.c -o exploit
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: exploit-binary
        path: exploit
    
    - name: List Files
      run: ls -la
